name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    if: github.repository == 'quitsmx/test1'
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
        # La versión de pnpm está en package.json#packageManager

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'

      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Publish GitHub Release
        uses: release-drafter/release-drafter@v6
        if: ${{ contains(steps.get-latest-tag.outputs.tag, steps.version.outputs.value) == false }}
        with:
          version: ${{ steps.version.outputs.value }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        if: ${{ contains(steps.get-latest-tag.outputs.tag, steps.version.outputs.value) == false }}
        run: pnpm publish --access public --no-git-checks --report-summary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
